default_install_hook_types: ["pre-commit", "commit-msg", "post-checkout"]
default_stages: ["pre-commit", "pre-push"]
fail_fast: false
repos:
  - repo: local
    hooks:
      - id: update-precommit
        name: update-precommit
        entry: bash -c "pre-commit autoupdate"
        language: system
        stages:
          - "post-checkout"
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        alias: "whitespace"
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: no-commit-to-branch
        args:
          - "-b"
          - "main"
          # - "staging"
          # - "-b"

  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      - id: go-test-mod

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: golangci-lint
        args:
          - "--fix"

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.13.0
    hooks:
      - id: commitizen
        stages: ["commit-msg"]
      - id: commitizen-branch
        stages: [push]
